spring.application.name=ExpenseJar

spring.datasource.url=jdbc:mysql://localhost:3306/expensejar
spring.datasource.username=root
spring.datasource.password=170208

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081